<?php
// QUIZLY Automated AI Question Generator Test Suite
// Validates OpenRouter integration, untrusted JSON parsing, prompt validation,
// duplicate detection, multi-tenant isolation, and database transactional persistence.

require_once __DIR__ . '/config/config.php';
require_once __DIR__ . '/config/database.php';
require_once __DIR__ . '/services/OpenRouterClient.php';
require_once __DIR__ . '/services/AIQuestionGenerator.php';

echo "========================================================\n";
echo "🤖 QUIZLY AI QUESTION GENERATOR AUTOMATED TEST SUITE\n";
echo "========================================================\n\n";

$passCount = 0;
$failCount = 0;

function assertAiTest(bool $condition, string $testName, string $details = ''): void {
    global $passCount, $failCount;
    if ($condition) {
        $passCount++;
        echo "  ✅ [PASS] $testName\n";
        if ($details) echo "     └─ $details\n";
    } else {
        $failCount++;
        echo "  ❌ [FAIL] $testName\n";
        if ($details) echo "     └─ ERROR: $details\n";
    }
}

$db = Database::getConnection();

// -------------------------------------------------------------
// TEST GROUP 1: OPENROUTER CLIENT UNIT TESTS
// -------------------------------------------------------------
echo "1. Testing OpenRouter Client & Configuration...\n";

$client = new OpenRouterClient();
assertAiTest($client->isConfigured(), "OpenRouter client loaded API key from environment", "Model: " . $client->getModel());

// Test unconfigured client error handling
$emptyClient = new OpenRouterClient('', 'openrouter/free');
$missingKeyCaught = false;
try {
    $emptyClient->chatCompletion([['role' => 'user', 'content' => 'hi']]);
} catch (Exception $e) {
    if (str_contains($e->getMessage(), 'AI generation is not configured')) {
        $missingKeyCaught = true;
    }
}
assertAiTest($missingKeyCaught, "Missing API key throws sanitized platform administrator exception");

// Test Live Chat Completion via configured OpenRouter API
$liveSuccess = false;
$liveSnippet = '';
try {
    $res = $client->chatCompletion([
        ['role' => 'user', 'content' => 'Return ONLY a JSON object: {"status": "ok"}']
    ], ['temperature' => 0.1, 'max_tokens' => 300]);
    $content = $client->extractContent($res);
    $decoded = json_decode($content, true);
    if (isset($decoded['status']) && $decoded['status'] === 'ok') {
        $liveSuccess = true;
        $liveSnippet = $content;
    }
} catch (Throwable $e) {
    $liveSnippet = $e->getMessage();
}
assertAiTest($liveSuccess, "Live OpenRouter completions endpoint successfully responds to user API key", $liveSnippet);

echo "\n";

// -------------------------------------------------------------
// TEST GROUP 2: UNTRUSTED AI OUTPUT PARSING & SCHEMA VALIDATION
// -------------------------------------------------------------
echo "2. Testing AI Untrusted JSON Parsing & Strict Schema Sanitization...\n";

$generator = new AIQuestionGenerator($client, $db);

// Scenario A: JSON wrapped in markdown code fences with extra commentary
$wrappedJson = <<<EOT
Here are your requested quiz questions:
```json
{
  "questions": [
    {
      "question_text": "Which OSI layer is responsible for routing packets across network boundaries?",
      "question_type": "multiple_choice",
      "difficulty": "medium",
      "topic": "Networking",
      "options": [
        {"text": "Network Layer", "is_correct": true},
        {"text": "Transport Layer", "is_correct": false},
        {"text": "Data Link Layer", "is_correct": false},
        {"text": "Physical Layer", "is_correct": false}
      ],
      "explanation": "The network layer (Layer 3) handles packet forwarding and routing.",
      "learning_objective": "Understand OSI Layer 3 functions."
    }
  ]
}
```
Hope this helps your students!
EOT;

$parsedA = $generator->parseAndValidateQuestionsJson($wrappedJson, 1);
assertAiTest(count($parsedA) === 1, "Strips markdown code fences and extraneous text cleanly");
assertAiTest($parsedA[0]['options'][0]['is_correct'] === true, "Preserves correct option flag");
assertAiTest($parsedA[0]['options'][0]['key'] === 'A', "Assigns standard alphabetical option keys (A, B, C, D)");

// Scenario B: MCQ with multiple correct answers mistakenly generated by AI -> auto-corrected to exactly 1
$badMcqJson = json_encode([
    'questions' => [
        [
            'question_text' => 'What is the default HTTP port?',
            'question_type' => 'multiple_choice',
            'options' => [
                ['text' => '80', 'is_correct' => true],
                ['text' => '8080', 'is_correct' => true], // Erroneous second correct
                ['text' => '443', 'is_correct' => false],
                ['text' => '21', 'is_correct' => false]
            ]
        ]
    ]
]);

$parsedB = $generator->parseAndValidateQuestionsJson($badMcqJson, 1);
$bCorrectCount = 0;
foreach ($parsedB[0]['options'] as $opt) {
    if ($opt['is_correct']) $bCorrectCount++;
}
assertAiTest($bCorrectCount === 1, "Enforces EXACTLY ONE correct answer for single-choice MCQ");

// Scenario C: True / False structure enforcement
$tfJson = json_encode([
    'questions' => [
        [
            'question_text' => 'UDP is a connectionless transport protocol.',
            'question_type' => 'true_false',
            'options' => [
                ['text' => 'True', 'is_correct' => true],
                ['text' => 'False', 'is_correct' => false]
            ]
        ]
    ]
]);

$parsedC = $generator->parseAndValidateQuestionsJson($tfJson, 1);
assertAiTest(count($parsedC[0]['options']) === 2 && $parsedC[0]['question_type'] === 'true_false', "Enforces exactly 2 options for True/False questions");

// Scenario D: Duplicate options within a question -> auto-deduplicated
$dupOptJson = json_encode([
    'questions' => [
        [
            'question_text' => 'Select the primary colors.',
            'question_type' => 'multiple_choice',
            'options' => [
                ['text' => 'Red', 'is_correct' => true],
                ['text' => 'Red', 'is_correct' => false], // Duplicate!
                ['text' => 'Blue', 'is_correct' => false],
                ['text' => 'Green', 'is_correct' => false]
            ]
        ]
    ]
]);
$parsedD = $generator->parseAndValidateQuestionsJson($dupOptJson, 1);
$optTexts = array_map(fn($o) => $o['text'], $parsedD[0]['options']);
assertAiTest(count($optTexts) === count(array_unique($optTexts)), "Deduplicates options within a question");

// Scenario E: Malformed JSON throws user-friendly exception
$malformedThrown = false;
try {
    $generator->parseAndValidateQuestionsJson("This is definitely not valid JSON", 1);
} catch (Exception $e) {
    if (str_contains($e->getMessage(), 'invalid response')) {
        $malformedThrown = true;
    }
}
assertAiTest($malformedThrown, "Malformed AI response safely caught and rejected");

echo "\n";

// -------------------------------------------------------------
// TEST GROUP 3: DUPLICATE QUESTION DETECTION ENGINE
// -------------------------------------------------------------
echo "3. Testing Organization Duplicate Question Detection...\n";

// Insert a known question in organization 1 to test detection
$testQuizTitle = "Duplicate Detection Fixture Quiz " . time();
$db->exec("INSERT INTO quizzes (organization_id, creator_id, title, category, difficulty, status) VALUES (1, 1, '{$testQuizTitle}', 'Networking', 'MEDIUM', 'DRAFT')");
$fixtureQuizId = (int)$db->lastInsertId();

$fixturePrompt = "What is the primary function of the Address Resolution Protocol (ARP)?";
$db->exec("INSERT INTO questions (quiz_id, question_text, timer_seconds, max_points, order_num) VALUES ({$fixtureQuizId}, '{$fixturePrompt}', 20, 1000, 1)");
$fixtureQuestionId = (int)$db->lastInsertId();

$testGenerated = [
    [
        'id' => 'gen_1',
        'question_text' => 'What is the primary function of the Address Resolution Protocol (ARP)?', // Exact match
        'question_type' => 'multiple_choice',
        'difficulty' => 'medium',
        'topic' => 'Networking',
        'options' => [['key' => 'A', 'text' => 'Map IP to MAC', 'is_correct' => true], ['key' => 'B', 'text' => 'DNS', 'is_correct' => false]]
    ],
    [
        'id' => 'gen_2',
        'question_text' => 'What is the function of the Address Resolution Protocol ARP?', // Near duplicate
        'question_type' => 'multiple_choice',
        'difficulty' => 'medium',
        'topic' => 'Networking',
        'options' => [['key' => 'A', 'text' => 'Map IP to MAC', 'is_correct' => true], ['key' => 'B', 'text' => 'DNS', 'is_correct' => false]]
    ],
    [
        'id' => 'gen_3',
        'question_text' => 'How does the Three-Way Handshake establish a TCP connection?', // Unique
        'question_type' => 'multiple_choice',
        'difficulty' => 'medium',
        'topic' => 'Networking',
        'options' => [['key' => 'A', 'text' => 'SYN, SYN-ACK, ACK', 'is_correct' => true], ['key' => 'B', 'text' => 'RST', 'is_correct' => false]]
    ]
];

$checked = $generator->detectDuplicates($testGenerated, 1);
assertAiTest($checked[0]['is_duplicate'] === true, "Exact duplicate detected and flagged", $checked[0]['duplicate_warning']);
assertAiTest($checked[1]['is_duplicate'] === true, "High similarity near-duplicate detected and flagged", $checked[1]['duplicate_warning']);
assertAiTest($checked[2]['is_duplicate'] === false, "Distinct question correctly cleared without duplicate flag", $checked[2]['duplicate_warning'] ?? '');

echo "\n";

// -------------------------------------------------------------
// TEST GROUP 4: DATABASE TRANSACTION & PERSISTENCE
// -------------------------------------------------------------
echo "4. Testing Database Transactional Persistence & Metadata...\n";

$approvedBatch = [
    [
        'question_text' => 'Which protocol provides secure encrypted transport for web traffic?',
        'question_type' => 'multiple_choice',
        'difficulty' => 'easy',
        'topic' => 'Web Security',
        'explanation' => 'HTTPS uses TLS/SSL to encrypt HTTP traffic.',
        'learning_objective' => 'Identify secure web protocols.',
        'timer_seconds' => 15,
        'max_points' => 1000,
        'options' => [
            ['key' => 'A', 'text' => 'HTTPS', 'is_correct' => true],
            ['key' => 'B', 'text' => 'HTTP', 'is_correct' => false],
            ['key' => 'C', 'text' => 'FTP', 'is_correct' => false],
            ['key' => 'D', 'text' => 'Telnet', 'is_correct' => false]
        ]
    ]
];

$saveResult = $generator->saveApprovedQuestions($approvedBatch, 1, 1, null, "AI Cybersecurity Quiz " . time());
assertAiTest($saveResult['saved_count'] === 1 && $saveResult['quiz_id'] > 0, "Approved AI question saved to database with new Quiz ID: {$saveResult['quiz_id']}");

$savedQuizId = $saveResult['quiz_id'];
$stmtVerify = $db->prepare("
    SELECT q.*, (SELECT COUNT(*) FROM question_options WHERE question_id = q.id) AS opt_count
    FROM questions q 
    WHERE q.quiz_id = :quiz_id
");
$stmtVerify->execute(['quiz_id' => $savedQuizId]);
$savedRow = $stmtVerify->fetch(PDO::FETCH_ASSOC);

assertAiTest((int)$savedRow['ai_generated'] === 1, "Question stored with ai_generated = 1 flag");
assertAiTest($savedRow['generation_source'] === 'openrouter', "Question stored with generation_source = 'openrouter'");
assertAiTest(!empty($savedRow['ai_model']), "Question stored with ai_model: " . $savedRow['ai_model']);
assertAiTest(!empty($savedRow['generation_timestamp']), "Question stored with generation_timestamp");
assertAiTest((int)$savedRow['opt_count'] === 4, "Question options stored successfully (4 options)");
assertAiTest($savedRow['explanation'] === 'HTTPS uses TLS/SSL to encrypt HTTP traffic.', "Explanation stored accurately");

echo "\n";

// -------------------------------------------------------------
// TEST GROUP 5: MULTI-TENANT AUTHORIZATION & PERMISSION ISOLATION
// -------------------------------------------------------------
echo "5. Testing Multi-Tenant Authorization & Tenant Isolation...\n";

$crossOrgBlocked = false;
try {
    // Attempt to save questions into an organization 2 quiz from organization 1 context
    $db->exec("INSERT INTO quizzes (organization_id, creator_id, title) VALUES (2, 3, 'Org 2 Protected Quiz')");
    $org2QuizId = (int)$db->lastInsertId();

    $generator->saveApprovedQuestions($approvedBatch, 1, 1, $org2QuizId);
} catch (Throwable $e) {
    if (str_contains($e->getMessage(), 'unauthorized') || str_contains($e->getMessage(), 'not found')) {
        $crossOrgBlocked = true;
    }
}
assertAiTest($crossOrgBlocked, "Cross-organization target quiz access is strictly blocked");

// Clean up test fixtures
try {
    $db->exec("DELETE FROM quizzes WHERE id IN ({$fixtureQuizId}, {$savedQuizId})");
} catch (Throwable $t) {}

echo "\n";
echo "========================================================\n";
echo "📊 AI SUITE SUMMARY: $passCount PASSED, $failCount FAILED\n";
echo "========================================================\n";

if ($failCount === 0) {
    echo "🎉 ALL AI GENERATOR, VALIDATION & PERSISTENCE TESTS PASSED SUCCESSFULLY!\n";
    exit(0);
} else {
    echo "⚠️ SOME TESTS FAILED. PLEASE REVIEW LOGS ABOVE.\n";
    exit(1);
}
